### ISSUE TITLE
Using dataclass and multiple dispatch with constructor

### ISSUE THREAD

**Issue by itsdfish** [erezsh/runtype#24]
Thank you for putting this package together. It is very useful. 

One problem I ran into is using dataclass with multiple dispatch on the constructor. Here is an example:

**Example**
```
from runtype import Dispatch 
from runtype import dataclass

dp = Dispatch()

@dataclass 
class SomeType:
    
    x: int = 1
    y: int = 1

@dataclass
class MyClass:
    
    x: int = 0
    y: int = 0
    
    @dp
    def __init__(self, some_type : SomeType):
        self.x = some_type.x
        self.y = some_type.y
```
 
 **Error**
 
```
 MyClass()
Traceback (most recent call last):

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 84, in find_function_cached
    return self._cache[sig]

KeyError: (<class '__main__.MyClass'>,)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/tmp/ipykernel_54810/2409861197.py", line 1, in <module>
    MyClass()

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 36, in dispatched_f
    f = root.find_function_cached(args)

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 86, in find_function_cached
    f = self.find_function(args)

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 72, in find_function
    raise DispatchError(f"Function '{self.name}' not found for signature {self.get_arg_types(args)}")

DispatchError: Function '__init__' not found for signature (<class '__main__.MyClass'>,)
 
```

It would be nice to use dataclass and multiple dispatch together, but its not clear to me if that is possible.

**Comment by itsdfish** [comment]
My apologies. I just realized the problem is more fundamental. It appears that multiple dispatch is not working on constructors:

```
from runtype import Dispatch 
from runtype import dataclass

dp = Dispatch()


class MyClass:
    
    @dp
    def __init__(self, x: int, y: int):
        self.x = x
        self.y = y
    

```

**Comment by erezsh** [comment]
Hi @itsdfish , glad you like it!

Dispatch surely does work for constructors:

```python

from runtype import Dispatch

dp = Dispatch()

class Color:
    @dp
    def __init__(self, hex: str):
        self.hex = hex

    @dp
    def __init__(self, r: int, g:int, b: int):
        self.hex = '#%02x%02x%02x' % (r,g,b)


a = Color(10, 20, 30)
b = Color('#abc')

print(a.hex, b.hex) # Prints: #0a141e #abc
```

As for the code you posted, it also works with a minor change:

```python
from runtype import Dispatch 
from runtype import dataclass

dp = Dispatch()

@dataclass 
class SomeType:
    
    x: int = 1
    y: int = 1

@dataclass(frozen=False)
class MyClass:
    
    x: int = 0
    y: int = 0
    
    @dp
    def __init__(self, some_type : SomeType):
        self.x = some_type.x
        self.y = some_type.y


print( MyClass(SomeType(10, 20)) )  # MyClass(x=10, y=20)
```
Make sure you're using the latest version of runtype (0.3.1)

**Comment by itsdfish** [comment]
@erezsh, thank you for your reply. I see that the explicit constructor works with your change, but the constructor created by dataclass does not appear to work.  Here is the error that I receive:

```
MyClass() # use default values x = 0, y = 0
Traceback (most recent call last):

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 84, in find_function_cached
    return self._cache[sig]

KeyError: (<class '__main__.MyClass'>,)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/tmp/ipykernel_54804/2188126193.py", line 1, in <module>
    MyClass() # use default values x = 0, y = 0

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 36, in dispatched_f
    f = root.find_function_cached(args)

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 86, in find_function_cached
    f = self.find_function(args)

  File "/home/dfish/anaconda3/lib/python3.8/site-packages/runtype/dispatch.py", line 72, in find_function
    raise DispatchError(f"Function '{self.name}' not found for signature {self.get_arg_types(args)}")

DispatchError: Function '__init__' not found for signature (<class '__main__.MyClass'>,)
```

One workaround is to define the default values within the constructor function definition:

```
from runtype import Dispatch 
from runtype import dataclass

dp = Dispatch()

@dataclass 
class SomeType:
    
    x: int = 1
    y: int = 1

@dataclass(frozen=False)
class MyClass:

    @dp
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
        
    @dp
    def __init__(self, some_type : SomeType):
        self.x = some_type.x
        self.y = some_type.y

```

I think the workaround is fine, but it might be good to document as it may work differently than one may expect. 

Thanks again for your reply.

**Comment by erezsh** [comment]
Oh, right, when you implement `__init__`, the dataclass won't create its own. From https://docs.python.org/3/library/dataclasses.html: 

```
If the class already defines __init__(), this parameter is ignored.
```

It could be a nice little feature, to add it anyway if `__init__` is a dispatched function.

**Comment by erezsh** [comment]
This issue has been solved. See the latest release (0.3.5)

Note: iirc you'll have to call `__post_init__()` yourself, if you want runtype's type checking to run.
