### ISSUE TITLE
Dispatch and Runtype Dataclasses

### ISSUE THREAD

**Issue by Syndog** [erezsh/runtype#27]
In #24 you mentioned how multiple dispatch works fine for constructors.  To demonstrate, you introduced a `Color` class that exhibits this behavior...

```
from runtype import Dispatch

dp = Dispatch()

class Color:
    @dp
    def __init__(self, hex: str):
        self.hex = hex

    @dp
    def __init__(self, r: int, g:int, b: int):
        self.hex = '#%02x%02x%02x' % (r,g,b)


a = Color(10, 20, 30)
b = Color('#abc')

print(a.hex, b.hex) # Prints: #0a141e #abc
```

Experimenting with your example, I tried making the `Color` class into a `dataclasses.dataclass`, and it still worked great!  However, when I made it into a `runtype.dataclass`, I received the following error...

```
Traceback (most recent call last):
  File "C:\Work\temp-runtype\main.py", line 20, in <module>
    a = Color(10, 20, 30)
  File "C:\Users\owner\AppData\Local\pypoetry\Cache\virtualenvs\temp-runtype-7V6D2ZSe-py3.10\lib\site-packages\runtype\dispatch.py", line 37, in dispatched_f
    return f(*args, **kw)
  File "C:\Work\temp-runtype\main.py", line 17, in __init__
    self.hex = '#%02x%02x%02x' % (r,g,b)
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'hex'
```

A curious thing to discover from runtype's own dataclass decorator.  Is this a bug, or have I missed something?

**Comment by Syndog** [comment]
Ah, I see I did miss something.  runtype.dataclass is frozen by default.  To change this, I can switch the decorator to `dataclass(frozen=False)`
