### ISSUE TITLE
No support for type Literal error when using typing_extensions >= 4.6.0

### ISSUE THREAD

**Issue by apirogov** [erezsh/runtype#35]
This worked up to `typing_extensions` version `4.5.0`:

```python
from runtype import is_subtype
from typing_extensions import Literal
is_subtype(Literal[1], Literal[1, 2])
```

Now with typing_extensions 4.6.0 and upward (and Python 3.8) I get this:

```
Traceback (most recent call last):
  File "/local/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.8/lib/python3.8/site-packages/runtype/pytypes.py", line 541, in to_canon
    return self.cache[t]
KeyError: typing_extensions.Literal[1]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.8/lib/python3.8/site-packages/runtype/pytypes.py", line 544, in to_canon
    res = _type_cast_mapping[t]
KeyError: typing_extensions.Literal[1]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.8/lib/python3.8/site-packages/runtype/validation.py", line 28, in is_subtype
    ct1 = type_caster.to_canon(t1)
  File "/local/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.8/lib/python3.8/site-packages/runtype/pytypes.py", line 546, in to_canon
    res = self._to_canon(t)
  File "/local/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.8/lib/python3.8/site-packages/runtype/pytypes.py", line 532, in _to_canon
    raise NotImplementedError("No support for type:", t)
NotImplementedError: ('No support for type:', typing_extensions.Literal[1])
```

**Comment by erezsh** [comment]
I just tested this with `typing_extensions==4.10.0` and Python 3.11, and it works.

If this is still an issue, please feel free to comment and reopen the issue.
